name: tenv
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - expat=2.7.3=h7354ed3_4
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.25=h0dcde21_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py39h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - anyio==4.12.0
      - certifi==2025.11.12
      - chardet==3.0.4
      - dotenv==0.9.9
      - exceptiongroup==1.3.1
      - googletrans==4.0.0rc1
      - h11==0.9.0
      - h2==3.2.0
      - hpack==3.0.0
      - hstspreload==2025.1.1
      - httpcore==0.9.1
      - httpx==0.13.3
      - hyperframe==5.2.0
      - idna==2.10
      - numpy==2.0.2
      - pandas==2.3.3
      - pyaes==1.6.1
      - pyasn1==0.6.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-telegram-bot==20.3
      - pytz==2025.2
      - rfc3986==1.5.0
      - rsa==4.9.1
      - six==1.17.0
      - sniffio==1.3.1
      - telethon==1.42.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - tzdata==2025.3
prefix: /home/jay.ponda/miniconda3/envs/tenv
