name: tenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.25
  - pip
  - numpy=1.26.4
  - pandas=2.3.3
  - openpyxl=3.1.5
  - pip:
    - anyio
    - certifi==2025.11.12
    - dotenv==0.9.9
    - googletrans-py
    - httpx
    - requests
    - langdetect==1.0.9
    - python-telegram-bot==20.3
    - telethon==1.42.0
    - tqdm==4.67.1
    - python-dotenv==1.2.1
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - pydantic==2.5.0